[package]
name = "convert"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pest_meta = "2.7"
# pest_meta = { version = "2.7", features = ["not-bootstrap-in-src"] }
